// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7tHrnOHtWE9rbTRqtoEWc9Ndt4nCfJqY',
    appId: '1:362309733205:web:dea9a508a3ae90b3163ddc',
    messagingSenderId: '362309733205',
    projectId: 'awalnya-gabut',
    authDomain: 'awalnya-gabut.firebaseapp.com',
    storageBucket: 'awalnya-gabut.appspot.com',
    measurementId: 'G-Q3YQ16Y1DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLg6W29ypKlZtrDptJ-kevDbVQqW27ls',
    appId: '1:362309733205:android:b38369bf1b7a6cf6163ddc',
    messagingSenderId: '362309733205',
    projectId: 'awalnya-gabut',
    storageBucket: 'awalnya-gabut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGY75eZdhIwL7nAUNeY0AeDoZVI4LoXzE',
    appId: '1:362309733205:ios:8e66fa59543b3068163ddc',
    messagingSenderId: '362309733205',
    projectId: 'awalnya-gabut',
    storageBucket: 'awalnya-gabut.appspot.com',
    iosBundleId: 'com.example.ecoww',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGY75eZdhIwL7nAUNeY0AeDoZVI4LoXzE',
    appId: '1:362309733205:ios:8e66fa59543b3068163ddc',
    messagingSenderId: '362309733205',
    projectId: 'awalnya-gabut',
    storageBucket: 'awalnya-gabut.appspot.com',
    iosBundleId: 'com.example.ecoww',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7tHrnOHtWE9rbTRqtoEWc9Ndt4nCfJqY',
    appId: '1:362309733205:web:ebef09314b2ab363163ddc',
    messagingSenderId: '362309733205',
    projectId: 'awalnya-gabut',
    authDomain: 'awalnya-gabut.firebaseapp.com',
    storageBucket: 'awalnya-gabut.appspot.com',
    measurementId: 'G-X58R676CF6',
  );
}
